"use client";
import { useState, useEffect, useRef } from "react";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import { useMicroInteractions } from "../hooks/useMicroInteractions";
import { trackEvent } from "../lib/fbq";

// ─── Constants ────────────────────────────────────────────────────────────────

const AI_RESPONSE =
  "Based on reviews and online presence, top-rated plumbers in Fort Worth include Rescue Rooter, Milestone Electric & Plumbing, and Benjamin Franklin Plumbing.";
const AI_WORDS = AI_RESPONSE.split(" ");

const TRADES = [
  "Plumbing",
  "HVAC",
  "Roofing",
  "Electrical",
  "General Contracting",
  "Custom Home Builder",
  "Landscaping",
  "Pest Control",
  "Foundation / Concrete",
  "Tree Service",
  "Garage Doors",
  "Other",
];

const SIGNALS = [
  {
    acro: "GEO",
    label: "Generative Engine Optimization",
    desc: "Whether Google's AI Overview names your business when someone searches your trade in your city — or skips straight to a competitor.",
  },
  {
    acro: "AEO",
    label: "Answer Engine Optimization",
    desc: "Whether ChatGPT and Perplexity name your business when someone asks for a contractor in your market.",
  },
  {
    acro: "LEO",
    label: "Local Entity Optimization",
    desc: "Whether your Google Business Profile and directory listings are strong and consistent enough for AI to trust what they say about you.",
  },
  {
    acro: "VEO",
    label: "Voice Engine Optimization",
    desc: "What Siri, Alexa, and Google Assistant recommend when someone asks for your trade near your city.",
  },
  {
    acro: "PEO",
    label: "Prompt Engine Optimization",
    desc: "Whether AI has enough clear, public information about your business to recommend you by name instead of guessing.",
  },
  {
    acro: "IEO",
    label: "Index Engine Optimization",
    desc: "Whether AI crawlers can even read your site well enough to cite it at all.",
  },
];

const PROOF = [
  {
    title: "WHERE YOU DISAPPEAR",
    desc: "See exactly which AI-driven research stages your ideal customer goes through — and where you disappear from their consideration set.",
  },
  {
    title: "WHO'S TAKING YOUR CALLS",
    desc: "Know which platforms own the citations in your market and the threat level each one represents to your visibility right now.",
  },
  {
    title: "WHAT TO FIX FIRST",
    desc: "A prioritized action sequence built for your specific gaps — not a generic checklist, a sequenced plan you can execute immediately.",
  },
];

const FAQS = [
  {
    q: "Is this the same as a free AI checker?",
    a: "No. Free tools return generic scores. This brief is generated by the same intelligence system 6Signal uses for retainer clients — specific to your business name, URL, trade, and city. The buyer journey, citation gaps, and competitive landscape are built for your market.",
  },
  {
    q: "How long does it take?",
    a: "Your brief generates in under 60 seconds after payment and appears immediately on screen. You can download a PDF and review it on your own time.",
  },
  {
    q: "Why do you only work with one business per trade?",
    a: "Exclusivity is part of how 6Signal works, not a sales tactic. We take one contractor per trade per market — one plumber, one HVAC company, one roofer per city. If your trade is already placed in your market, we'll tell you before you buy anything.",
  },
  {
    q: "What if I want help acting on the results?",
    a: "Your results page gives you two options: a Full Strategy Brief for $97 that turns your gaps into an exact implementation plan, or a 1-Hour Strategy Call for $197 where we walk through your brief live and you leave with a clear execution decision.",
  },
  {
    q: "Is this a subscription?",
    a: "No. $27 one time. You get the brief. No recurring charges.",
  },
  {
    q: "What if something goes wrong?",
    a: "After payment you also receive an email with a permanent link to your brief, so you can reopen it on any device. If generation fails and we can't recover it, we regenerate it or refund the $27 — no back-and-forth, just email hello@6signal.co.",
  },
  {
    q: "Who is 6Signal?",
    a: "6Signal is a DFW-based AI visibility practice that works exclusively with contractors and local service businesses. We built the 6-Signal framework to map and close the gaps that cause local businesses to disappear from AI-generated recommendations.",
  },
];

// ─── Mock Chat Animation ──────────────────────────────────────────────────────

function MockChat() {
  const [showUser, setShowUser] = useState(false);
  const [showTyping, setShowTyping] = useState(false);
  const [wordCount, setWordCount] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [faded, setFaded] = useState(false);

  useEffect(() => {
    const isMobile = window.matchMedia("(max-width: 767px)").matches;

    if (isMobile) {
      setShowUser(true);
      setWordCount(AI_WORDS.length);
      setShowResult(true);
      return;
    }

    const allTimers: ReturnType<typeof setTimeout>[] = [];
    const add = (fn: () => void, ms: number) => {
      const id = setTimeout(fn, ms);
      allTimers.push(id);
    };

    const runSequence = () => {
      setShowUser(false);
      setShowTyping(false);
      setWordCount(0);
      setShowResult(false);
      setFaded(false);

      add(() => setShowUser(true), 300);
      add(() => setShowTyping(true), 1200);
      add(() => {
        setShowTyping(false);
        AI_WORDS.forEach((_, i) => add(() => setWordCount(i + 1), i * 80));
      }, 2500);
      add(() => setShowResult(true), 5200);
      add(() => setFaded(true), 8000);
      add(() => runSequence(), 10000);
    };

    runSequence();
    return () => allTimers.forEach(clearTimeout);
  }, []);

  return (
    <div className={`vc2-mock${faded ? " vc2-mock--faded" : ""}`}>
      <div className="vc2-mock-header">
        <span className="vc2-mock-dot vc2-mock-dot--red" />
        <span className="vc2-mock-dot vc2-mock-dot--yellow" />
        <span className="vc2-mock-dot vc2-mock-dot--green" />
        <span className="vc2-mock-title">AI Search</span>
      </div>
      <div className="vc2-mock-body">
        {showUser && (
          <div className="vc2-mock-row vc2-mock-row--user">
            <span className="vc2-mock-bubble">
              Who&rsquo;s the best plumber in Fort Worth TX?
            </span>
          </div>
        )}

        {showTyping && (
          <div className="vc2-mock-row vc2-mock-row--ai">
            <span className="vc2-mock-ai-label">AI</span>
            <div className="vc2-mock-typing">
              <span /><span /><span />
            </div>
          </div>
        )}

        {!showTyping && wordCount > 0 && (
          <div className="vc2-mock-row vc2-mock-row--ai">
            <span className="vc2-mock-ai-label">AI</span>
            <p className="vc2-mock-ai-text">
              {AI_WORDS.slice(0, wordCount).join(" ")}
            </p>
          </div>
        )}

        {showResult && (
          <div className="vc2-mock-result">
            Your business does not appear in these results.
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function VisibilityCheckPage() {
  useMicroInteractions();

  const [form, setForm] = useState({
    name: "",
    email: "",
    url: "",
    trade: "",
    city: "",
    competitors: "",
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [heroVisible, setHeroVisible] = useState(true);
  const heroRef = useRef<HTMLElement>(null);
  const partialLeadSent = useRef(false);

  // Sticky bar visibility — appears when hero scrolls out of view
  useEffect(() => {
    const el = heroRef.current;
    if (!el) return;
    const io = new IntersectionObserver(
      ([entry]) => setHeroVisible(entry.isIntersecting),
      { threshold: 0.1 }
    );
    io.observe(el);
    return () => io.disconnect();
  }, []);

  const validate = () => {
    const e: Record<string, string> = {};
    if (!form.name.trim()) e.name = "Business name is required";
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) e.email = "A valid email is required";
    if (!form.url.trim()) e.url = "Website URL is required";
    if (!form.trade) e.trade = "Please select your trade";
    if (!form.city.trim()) e.city = "City / market is required";
    return e;
  };

  const handleChange = (field: string, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) setErrors((prev) => ({ ...prev, [field]: "" }));
  };

  // Fires once, when the visitor leaves the email field with something
  // plausible in it — a signal that they're seriously filling this out even
  // if they never hit submit. Best-effort: never blocks or shows errors.
  const handleEmailBlur = () => {
    if (partialLeadSent.current) return;
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) return;
    partialLeadSent.current = true;
    fetch("/api/partial-lead", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
      keepalive: true,
    }).catch(() => { /* best-effort */ });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const errs = validate();
    if (Object.keys(errs).length > 0) {
      setErrors(errs);
      return;
    }
    setSubmitting(true);
    localStorage.removeItem("6sig_audit_result");
    localStorage.removeItem("6sig_strategy_result");
    localStorage.setItem(
      "6sig_audit_data",
      JSON.stringify({
        name: form.name,
        email: form.email,
        url: form.url,
        trade: form.trade,
        city: form.city,
        competitors: form.competitors,
      })
    );

    // Register the intake server-side so the purchase can always be linked
    // back to this form data (Stripe client_reference_id → recovery link).
    let intakeId: string | null = null;
    try {
      const r = await fetch("/api/intake", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      if (r.ok) intakeId = (await r.json())?.id ?? null;
    } catch { /* funnel works without it */ }
    if (intakeId) localStorage.setItem("6sig_intake_id", intakeId);

    trackEvent("InitiateCheckout", { value: 27.00, currency: "USD" });
    const stripeUrl = "https://buy.stripe.com/28EeVebRQ3J1ghz6bf3ks0p";
    window.location.href = intakeId
      ? `${stripeUrl}?client_reference_id=${intakeId}`
      : stripeUrl;
  };

  const scrollToForm = (e: React.MouseEvent) => {
    e.preventDefault();
    document.getElementById("audit-form")?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <div id="cursor-dot" aria-hidden="true" />
      <div id="cursor-ring" aria-hidden="true" />
      <Nav />

      {/* ── SECTION 1: HERO ─────────────────────────────── */}
      <header className="vc2-hero" ref={heroRef}>
        <div className="hero-glow" />
        <div className="wrap vc2-hero-inner">
          <div className="vc2-hero-left reveal">
            <span className="idx vc2-hero-eyebrow">AI Visibility Audit</span>
            <h1 className="display vc2-hero-headline">
              Find out if AI recommends
              <br />
              your business —{" "}
              <em>or your competitor.</em>
            </h1>
            <p className="vc2-hero-sub">
              Contractors losing work to AI invisibility don&rsquo;t know it
              yet. In 60 seconds, you will.
            </p>
            <button className="btn btn-primary btn-lg" onClick={scrollToForm}>
              Get My AI Visibility Brief — $27
              <svg
                className="arrow"
                viewBox="0 0 16 10"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.2"
              >
                <path d="M0 5h14M10 1l4 4-4 4" />
              </svg>
            </button>
            <span className="vc2-hero-trust">
              Results appear immediately after payment · PDF included · No
              subscription · Refund if it fails
            </span>
          </div>

          <div className="vc2-hero-right reveal">
            <MockChat />
          </div>
        </div>
      </header>

      {/* ── SECTION 2: FORM ──────────────────────────────── */}
      <section className="vc2-form-section rule" id="audit-form">
        <div className="wrap">
          <div className="vc2-form-head reveal">
            <h2 className="display vc2-form-headline">
              Enter your business details
            </h2>
            <p className="vc2-form-sub">
              Your brief is generated specifically for your business, your
              trade, and your market. This is not a template.
            </p>
          </div>

          <form className="vc2-form reveal" onSubmit={handleSubmit} noValidate>
            <div className="vc2-form-grid">
              {/* Business Name */}
              <div className={`vc2-field${errors.name ? " vc2-field--error" : ""}`}>
                <label className="vc2-label">
                  Business Name <span className="vc2-req">*</span>
                </label>
                <input
                  className="vc2-input"
                  type="text"
                  placeholder="Acme Plumbing"
                  value={form.name}
                  onChange={(e) => handleChange("name", e.target.value)}
                  autoComplete="organization"
                />
                {errors.name && (
                  <span className="vc2-error">{errors.name}</span>
                )}
              </div>

              {/* Email */}
              <div className={`vc2-field${errors.email ? " vc2-field--error" : ""}`}>
                <label className="vc2-label">
                  Email <span className="vc2-req">*</span>
                </label>
                <input
                  className="vc2-input"
                  type="email"
                  placeholder="you@yourbusiness.com"
                  value={form.email}
                  onChange={(e) => handleChange("email", e.target.value)}
                  onBlur={handleEmailBlur}
                  autoComplete="email"
                />
                {errors.email && (
                  <span className="vc2-error">{errors.email}</span>
                )}
              </div>

              {/* Website URL */}
              <div className={`vc2-field${errors.url ? " vc2-field--error" : ""}`}>
                <label className="vc2-label">
                  Website URL <span className="vc2-req">*</span>
                </label>
                <input
                  className="vc2-input"
                  type="text"
                  placeholder="https://yourbusiness.com"
                  value={form.url}
                  onChange={(e) => handleChange("url", e.target.value)}
                  autoComplete="url"
                />
                {errors.url && (
                  <span className="vc2-error">{errors.url}</span>
                )}
              </div>

              {/* Trade */}
              <div className={`vc2-field${errors.trade ? " vc2-field--error" : ""}`}>
                <label className="vc2-label">
                  Trade <span className="vc2-req">*</span>
                </label>
                <div className="vc2-select-wrap">
                  <select
                    className="vc2-select"
                    value={form.trade}
                    onChange={(e) => handleChange("trade", e.target.value)}
                  >
                    <option value="">Select your trade...</option>
                    {TRADES.map((t) => (
                      <option key={t} value={t}>
                        {t}
                      </option>
                    ))}
                  </select>
                  <svg
                    className="vc2-select-arrow"
                    viewBox="0 0 10 6"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.4"
                  >
                    <path d="M1 1l4 4 4-4" />
                  </svg>
                </div>
                {errors.trade && (
                  <span className="vc2-error">{errors.trade}</span>
                )}
              </div>

              {/* City */}
              <div className={`vc2-field${errors.city ? " vc2-field--error" : ""}`}>
                <label className="vc2-label">
                  City / Market <span className="vc2-req">*</span>
                </label>
                <input
                  className="vc2-input"
                  type="text"
                  placeholder="Fort Worth, TX"
                  value={form.city}
                  onChange={(e) => handleChange("city", e.target.value)}
                />
                {errors.city && (
                  <span className="vc2-error">{errors.city}</span>
                )}
              </div>

              {/* Competitor */}
              <div className="vc2-field vc2-field--full">
                <label className="vc2-label">
                  Top Competitor{" "}
                  <span className="vc2-optional">(optional)</span>
                </label>
                <input
                  className="vc2-input"
                  type="text"
                  placeholder="Competitor name — leave blank if unknown"
                  value={form.competitors}
                  onChange={(e) => handleChange("competitors", e.target.value)}
                />
              </div>
            </div>

            <div className="vc2-form-footer">
              <button
                className="btn btn-primary btn-lg vc2-submit"
                type="submit"
                disabled={submitting}
              >
                {submitting
                  ? "Preparing your brief..."
                  : "Get My AI Visibility Brief — $27"}
                {!submitting && (
                  <svg
                    className="arrow"
                    viewBox="0 0 16 10"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1.2"
                  >
                    <path d="M0 5h14M10 1l4 4-4 4" />
                  </svg>
                )}
              </button>
              <p className="vc2-form-note">
                Secure payment via Stripe. Brief generates immediately on-screen
                after checkout.
              </p>
            </div>
          </form>
        </div>
      </section>

      {/* ── SECTION 3: SIGNALS ───────────────────────────── */}
      <section className="vc2-signals-section rule">
        <div className="wrap">
          <div className="vc2-section-head reveal">
            <span className="idx">Where AI decides who gets the call</span>
            <h2 className="display vc2-section-headline">
              Six signals. Miss one, a competitor gets the job.
            </h2>
          </div>
          <div className="vc2-signals-grid">
            {SIGNALS.map((s) => (
              <div className="vc2-signal-item reveal" key={s.acro}>
                <div className="vc2-signal-acro">{s.acro}</div>
                <div className="vc2-signal-label">{s.label}</div>
                <p className="vc2-signal-desc">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SECTION 4: PROOF ─────────────────────────────── */}
      <section className="vc2-proof-section rule">
        <div className="wrap">
          <div className="vc2-section-head reveal">
            <span className="idx">Not a scorecard</span>
            <h2 className="display vc2-section-headline">
              This is an intelligence brief.
            </h2>
          </div>
          <div className="vc2-proof-grid">
            {PROOF.map((p, i) => (
              <div className="vc2-proof-item reveal" key={i}>
                <div className="vc2-proof-num">
                  {String(i + 1).padStart(2, "0")}
                </div>
                <h3 className="vc2-proof-title">{p.title}</h3>
                <p className="vc2-proof-desc">{p.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SECTION 5: FAQ ───────────────────────────────── */}
      <section className="vc2-faq-section rule">
        <div className="wrap">
          <div className="vc2-section-head reveal">
            <span className="idx">Before you buy</span>
            <h2 className="display vc2-section-headline">Common questions.</h2>
          </div>
          <div className="faq-list">
            {FAQS.map((item, i) => (
              <div className="faq-item reveal" key={i}>
                <div className="faq-q">
                  <span className="q-idx">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="q-text">{item.q}</span>
                  <span className="q-icon" aria-hidden="true" />
                </div>
                <div className="faq-a">
                  <div className="faq-a-inner">{item.a}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SECTION 6: FINAL CTA ─────────────────────────── */}
      <section className="vc2-final">
        <div className="wrap vc2-final-inner">
          <h2 className="display vc2-final-headline reveal">
            Your competitors are showing up.
            <br />
            <em>Find out if you are.</em>
          </h2>
          <p className="vc2-final-sub reveal">
            $27 · Results in 60 seconds · PDF included · Refund if it fails
          </p>
          <button
            className="btn btn-primary btn-lg reveal"
            onClick={scrollToForm}
          >
            Get My AI Visibility Brief — $27
            <svg
              className="arrow"
              viewBox="0 0 16 10"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.2"
            >
              <path d="M0 5h14M10 1l4 4-4 4" />
            </svg>
          </button>
        </div>
      </section>

      <Footer />

      {/* ── MOBILE STICKY BAR ────────────────────────────── */}
      <div
        className={`vc2-sticky${!heroVisible ? " vc2-sticky--visible" : ""}`}
        aria-hidden={heroVisible}
      >
        <span className="idx vc2-sticky-label">AI Visibility Brief</span>
        <button className="btn btn-primary vc2-sticky-btn" onClick={scrollToForm}>
          Get My Brief — $27
        </button>
      </div>
    </>
  );
}
